[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache_forge"
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
local = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"
anvil = "http://127.0.0.1:8545"

[profile.deploy]
via_ir = false
